-- Run this in Supabase → SQL Editor.

create table if not exists public.point_transactions (
  id bigint generated by default as identity primary key,
  house_id text not null check (house_id in ('odysseus','achilles','circe','athena')),
  points integer not null check (points between -100 and 100 and points <> 0),
  reason text not null check (char_length(reason) between 1 and 80),
  teacher_name text not null check (teacher_name in ('Mx. Owens','Mrs. Wheelus','Mr. Dubin')),
  created_at timestamptz not null default now()
);

alter table public.point_transactions enable row level security;

-- Public/student page may read scores and activity.
create policy "Public can read point transactions"
on public.point_transactions
for select
to anon, authenticated
using (true);

-- Only signed-in teachers may add transactions.
create policy "Authenticated users can add point transactions"
on public.point_transactions
for insert
to authenticated
with check (
  teacher_name in ('Mx. Owens','Mrs. Wheelus','Mr. Dubin')
  and house_id in ('odysseus','achilles','circe','athena')
  and points between -100 and 100
  and points <> 0
);

-- No update/delete policy on purpose.
-- Corrections are made with an equal and opposite "Undo" transaction,
-- preserving an audit trail.

alter publication supabase_realtime add table public.point_transactions;
