const configured=!SUPABASE_URL.includes("YOUR_")&&!SUPABASE_ANON_KEY.includes("YOUR_");const db=configured?supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null,$=id=>document.getElementById(id);let action="award",selectedPoints=3,transactions=[];Object.entries(HOUSE_META).forEach(([id,h])=>$("houseId").add(new Option(h.name,id)));$("category").add(new Option("Choose category…",""));Object.keys(POINT_CATEGORIES).forEach(c=>$("category").add(new Option(c,c)));
function reasons(){$("reason").innerHTML="";if(!$("category").value){$("reason").add(new Option("Choose category first…",""));return}$("reason").add(new Option("Choose reason…",""));POINT_CATEGORIES[$("category").value].forEach(x=>$("reason").add(new Option(x,x)))}
$("category").onchange=()=>{reasons();$("otherReasonWrap").classList.add("hidden");confirmText()};$("reason").onchange=e=>{$("otherReasonWrap").classList.toggle("hidden",e.target.value!=="Other");confirmText()};
document.querySelectorAll(".action-toggle").forEach(b=>b.onclick=()=>{document.querySelectorAll(".action-toggle").forEach(x=>x.classList.remove("active"));b.classList.add("active");action=b.dataset.action;confirmText()});document.querySelectorAll(".point-btn").forEach(b=>b.onclick=()=>{document.querySelectorAll(".point-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");selectedPoints=+b.dataset.points;$("customPoints").value="";confirmText()});["teacherName","houseId","customPoints","otherReason"].forEach(x=>$(x).addEventListener("input",confirmText));
const amt=()=>+$("customPoints").value||selectedPoints,why=()=>$("reason").value==="Other"?$("otherReason").value.trim():$("reason").value;
function confirmText(){const t=$("teacherName").value,h=HOUSE_META[$("houseId").value],r=why(),a=amt(),v=action==="award"?"Award":"Deduct",p=action==="award"?"to":"from";$("confirmation").textContent=t&&h&&r?`${v} ${a} point${a===1?"":"s"} ${p} ${h.name} for ${r} — ${t}.`:"Choose a teacher, house, amount, and reason."}
function dash(){$("loginCard").classList.add("hidden");$("dashboard").classList.remove("hidden");$("logoutBtn").classList.remove("hidden");load()}function login(){$("loginCard").classList.remove("hidden");$("dashboard").classList.add("hidden");$("logoutBtn").classList.add("hidden")}
$("loginForm").onsubmit=async e=>{e.preventDefault();if(!configured){$("loginMessage").textContent="Add your Supabase URL and publishable key to config.js first.";return}const {error}=await db.auth.signInWithPassword({email:$("email").value,password:$("password").value});if(error){$("loginMessage").textContent=error.message;$("loginMessage").className="form-message error"}else dash()};$("logoutBtn").onclick=async()=>{await db.auth.signOut();login()};
$("pointsForm").onsubmit=async e=>{e.preventDefault();const t=$("teacherName").value,h=$("houseId").value,r=why(),a=amt();if(!t||!h||!r)return;$("pointsMessage").textContent="";const {error}=await db.from("point_transactions").insert({house_id:h,points:action==="award"?a:-a,reason:r,teacher_name:t});if(error){$("pointsMessage").textContent=error.message;$("pointsMessage").className="form-message error"}else{$("pointsMessage").textContent="Points recorded successfully.";$("pointsMessage").className="form-message success";$("category").value="";reasons();load()}};
function mon(){const d=new Date(),x=(d.getDay()+6)%7;d.setHours(0,0,0,0);d.setDate(d.getDate()-x);return d}function standings(s){return Object.entries(HOUSE_META).map(([id,h])=>({id,...h,points:s[id]||0})).sort((a,b)=>b.points-a.points).map(h=>`<div class="teacher-standing" style="--house:${h.color}"><strong>${h.symbol} ${h.name}</strong><strong>${h.points}</strong></div>`).join("")}
async function load(){const {data,error}=await db.from("point_transactions").select("*").order("created_at",{ascending:false});if(error)return;transactions=data||[];const a={odysseus:0,achilles:0,circe:0,athena:0},w={...a},m=mon();transactions.forEach(t=>{a[t.house_id]+=t.points;if(new Date(t.created_at)>=m)w[t.house_id]+=t.points});$("teacherStandings").innerHTML=standings(a);$("weeklyTeacherStandings").innerHTML=standings(w);analytics(w);history()}
function analytics(w){const m=mon(),r=transactions.filter(t=>new Date(t.created_at)>=m&&!t.reason.startsWith("Undo:")),p=r.filter(t=>t.points>0),c={};p.forEach(t=>c[t.reason]=(c[t.reason]||0)+t.points);const top=Object.entries(c).sort((a,b)=>b[1]-a[1])[0],lead=Object.entries(w).sort((a,b)=>b[1]-a[1])[0];$("analytics").innerHTML=`<div class="metric"><span>Weekly transactions</span><strong>${r.length}</strong></div><div class="metric"><span>Positive points</span><strong>${p.reduce((s,t)=>s+t.points,0)}</strong></div><div class="metric"><span>Top positive reason</span><strong>${top?top[0]:"—"}</strong></div><div class="metric"><span>Weekly leader</span><strong>${HOUSE_META[lead[0]].name}</strong></div>`}
function history(){$("historyList").innerHTML=transactions.slice(0,30).map(t=>{const h=HOUSE_META[t.house_id],sg=t.points>0?"+":"",tm=new Date(t.created_at).toLocaleString([],{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"});return `<div class="history-row"><strong class="${t.points<0?"error":""}">${sg}${t.points}</strong><div><strong>${h.name}</strong><div class="history-note">${t.reason} • ${tm}</div></div><div class="teacher-cell">${t.teacher_name}</div><button class="undo-btn" data-p="${t.points}" data-h="${t.house_id}" data-r="${encodeURIComponent(t.reason)}" data-t="${encodeURIComponent(t.teacher_name)}">Undo</button></div>`}).join("");document.querySelectorAll(".undo-btn").forEach(b=>b.onclick=async()=>{if(!confirm("Undo this transaction?"))return;await db.from("point_transactions").insert({house_id:b.dataset.h,points:-Number(b.dataset.p),reason:`Undo: ${decodeURIComponent(b.dataset.r)}`,teacher_name:decodeURIComponent(b.dataset.t)});load()})}
(async()=>{if(!configured)return login();const {data:{session}}=await db.auth.getSession();session?dash():login();db.auth.onAuthStateChange((_e,s)=>s?dash():login());db.channel("teacher").on("postgres_changes",{event:"*",schema:"public",table:"point_transactions"},load).subscribe()})();